#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nano'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='nano'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export LSCOLORS=GxBxhxDxfxhxhxhxhxcxcx
alias ls='ls -laghFG'
alias gs='git status'
alias gdh='git diff HEAD'
alias gpom='git push origin master'
alias gitback='git reset --soft HEAD~1'
alias glpretty="git log --date=iso --pretty=format:'%ad%x08%x08%x08%x08%x08%x08%x08%x08%x08%x08%x08%x08%x08%x08%aN %s'"
alias gtrack="git checkout --track -b"
alias gDel="git branch -D"
alias tcurl="curl -o /dev/null -s -w 'Total: %{time_total}\n'"
alias python=python3
alias mysql='mysql --pager="/usr/bin/less -SFX"'
alias glint='eslint --fix $(git diff --name-only HEAD | xargs)'
alias cotunnel='/Users/tamoyal/cotunnel/client/client'
alias gpstash='git stash && git pull origin main && git stash pop'
alias rails='bundle exec rails'
alias ruby='bundle exec ruby'
alias rake='bundle exec rake'
alias rubocop='bundle exec rubocop'
alias annotate='bundle exec annotate'
alias push='git push origin $(git rev-parse --abbrev-ref HEAD)'

export DISABLE_SPRING=true

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# https://github.com/microsoft/vscode/issues/140591
export NODE_OPTIONS=--openssl-legacy-provider

# https://stackoverflow.com/questions/75247041/ruby-3-0-4-with-postgres-14-throws-segmentation-fault
export PGGSSENCMODE="disable"
